version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: collab_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: always
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_DB: collab_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.localhost`)"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
    volumes:
      - nextcloud_data:/var/www/html

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: always
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres:5432
      - GITEA__database__NAME=collab_db
      - GITEA__database__USER=admin
      - GITEA__database__PASSWD=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.localhost`)"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
    volumes:
      - gitea_data:/data
    depends_on:
      - postgres

  jitsi-meet:
    image: jitsi/web
    container_name: jitsi-meet
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jitsi.rule=Host(`jitsi.localhost`)"
      - "traefik.http.services.jitsi.loadbalancer.server.port=80"

volumes:
  postgres_data:
  nextcloud_data:
  gitea_data:

